//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceGladiatorProjectApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Customer()
        {
            this.tbl_Card = new HashSet<tbl_Card>();
        }
    
        public int Customer_Id { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public string Email { get; set; }
        public string Phone_No { get; set; }
        public string Username { get; set; }
        public string Passwords { get; set; }
        public string Address { get; set; }
        public string Card_Type { get; set; }
        public string Select_Bank { get; set; }
        public string Saving_Account_No { get; set; }
        public string IFSC_Code { get; set; }
        public byte[] Documents { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Card> tbl_Card { get; set; }
    }
}
