//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceGladiatorProjectApp.Models
{
    using System;
    using System.Collections.Generic;
  using System.Runtime.Serialization;

  [DataContract]
    public partial class tbl_EMI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_EMI()
        {
            this.tbl_Transaction = new HashSet<tbl_Transaction>();
        }

    [DataMember]
        public int EMI_Id { get; set; }
    [DataMember]
    public Nullable<int> Tenure_period { get; set; }
    [DataMember]
    public Nullable<decimal> Product_cost { get; set; }
    [DataMember]
    public Nullable<decimal> Total_Amount_Paid { get; set; }
    [DataMember]
    public Nullable<int> Card_Id { get; set; }
    [DataMember]
    public Nullable<int> Product_Id { get; set; }
    [DataMember]
    public Nullable<System.DateTime> EMI_Due_Date { get; set; }
    [DataMember]
    public Nullable<System.DateTime> EMI_Start_Date { get; set; }
    [DataMember]
    public string prodName { get; set; }
    [DataMember]
    public Nullable<decimal> emiPerMonth { get; set; }
    
        public virtual tbl_Card tbl_Card { get; set; }
        public virtual tbl_Product tbl_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Transaction> tbl_Transaction { get; set; }
    }
}
