//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceGladiatorProjectApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Card()
        {
            this.tbl_EMI = new HashSet<tbl_EMI>();
        }
    
        public int Card_Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public string Card_Number { get; set; }
        public Nullable<System.DateTime> Valid_till { get; set; }
        public string Card_Type { get; set; }
        public Nullable<decimal> Total_credit { get; set; }
        public Nullable<int> Card_cost { get; set; }
        public string Status { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<decimal> credit_used { get; set; }
    
        public virtual tbl_Admin tbl_Admin { get; set; }
        public virtual tbl_Customer tbl_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EMI> tbl_EMI { get; set; }
    }
}
