//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceGladiatorProjectApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Transaction
    {
        public int Transaction_Id { get; set; }
        public Nullable<int> EMI_Id { get; set; }
        public string Product_Name { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public Nullable<decimal> Transaction_Amount { get; set; }
    
        public virtual tbl_EMI tbl_EMI { get; set; }
    }
}
