//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceGladiatorProjectApp.Models
{
    using System;
    using System.Collections.Generic;
  using System.Runtime.Serialization;

  [DataContract]
  public partial class tbl_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Customer()
        {
            this.tbl_Card = new HashSet<tbl_Card>();
        }

    [DataMember]
    public int Customer_Id { get; set; }
    [DataMember]
    public string Customer_Name { get; set; }
    [DataMember]
    public Nullable<System.DateTime> Date_of_Birth { get; set; }
    [DataMember]
    public string Email { get; set; }
    [DataMember]
    public string Phone_No { get; set; }
    [DataMember]
    public string Username { get; set; }
    [DataMember]
    public string Passwords { get; set; }
    [DataMember]
    public string Address { get; set; }
    [DataMember]
    public string Card_Type { get; set; }
    [DataMember]
    public string Select_Bank { get; set; }
    [DataMember]
    public string Saving_Account_No { get; set; }
    [DataMember]
    public string IFSC_Code { get; set; }
    [DataMember]
    public byte[] Documents { get; set; }
    [DataMember]
    public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Card> tbl_Card { get; set; }
    }
}
